// AUTO-GENERATED by gen_coeffs_n3.py  --  do not edit by hand
// Buck N=3 look-ahead coefficients (fixed R).
// Params: dt=1e-08, L=1e-05, C=0.0001, R=5.0, Vin_nom=12.0
// kL=1.000000e-03 kC=1.000000e-04 kR=2.000000e-05
package buck_coeffs_pkg;
  localparam int FRAC_C = 24;  // coefficient fractional bits
  localparam int FRAC_S = 16;  // state fractional bits

  // D3 = M3 - I, coefficient format Q*.FRAC_C (signed)
  localparam logic signed [31:0] D3_00 = -32'sd1014;
  localparam logic signed [31:0] D3_01 = 32'sd5033;
  localparam logic signed [31:0] D3_10 = -32'sd50330;
  localparam logic signed [31:0] D3_11 = -32'sd8;

  // u3_hat per unit Vin, format Q*.FRAC_C (signed). Index = {s_k,s_k1,s_k2}.
  // Multiply by Vin (state format) at runtime.
  localparam logic signed [31:0] U3V_0 = 32'sd0; // v, s=000
  localparam logic signed [31:0] U3I_0 = 32'sd0; // i, s=000
  localparam logic signed [31:0] U3V_1 = 32'sd1; // v, s=001
  localparam logic signed [31:0] U3I_1 = 32'sd16777; // i, s=001
  localparam logic signed [31:0] U3V_2 = 32'sd3; // v, s=010
  localparam logic signed [31:0] U3I_2 = 32'sd16777; // i, s=010
  localparam logic signed [31:0] U3V_3 = 32'sd3; // v, s=011
  localparam logic signed [31:0] U3I_3 = 32'sd33554; // i, s=011
  localparam logic signed [31:0] U3V_4 = 32'sd4; // v, s=100
  localparam logic signed [31:0] U3I_4 = 32'sd16777; // i, s=100
  localparam logic signed [31:0] U3V_5 = 32'sd5; // v, s=101
  localparam logic signed [31:0] U3I_5 = 32'sd33554; // i, s=101
  localparam logic signed [31:0] U3V_6 = 32'sd7; // v, s=110
  localparam logic signed [31:0] U3I_6 = 32'sd33554; // i, s=110
  localparam logic signed [31:0] U3V_7 = 32'sd8; // v, s=111
  localparam logic signed [31:0] U3I_7 = 32'sd50332; // i, s=111
endpackage
