// buck_core.sv  -  Buck mixed-precision Verlet twin (module only).
//
// Identical RTL to buck_verlet_mixed_precision.sv, but the COEFFICIENT PACKAGE
// (verlet_pkg) is external and auto-generated by tools/twin_gen.py from physical
// design params.  This is the prototyping-friendly form: to retarget the plant,
// regenerate the package - never hand-edit constants.
//
// Compile order:  gen/verlet_pkg.sv  (generated)  THEN  buck_core.sv
// Regenerate:
//   python tools/twin_gen.py buck --L 2.25e-6 --C 1.125e-6 --dt 10e-9 \
//       --steps 100 --kr-scale 3 --state-fmt Q6.12 --coef-fmt Q2.16 \
//       --out buck/lookahead/gen/verlet_pkg.sv
//
// See buck_verlet_mixed_precision.sv for the full datapath rationale.

import verlet_pkg::*;

module buck_verlet_mixed_precision (
    input  logic        clk,
    input  logic        rst_n,
    input  q2_16        kR,           // dynamic damping dt/RC (high-precision Q2.16)
    input  logic        s_k,          // 1-bit switch state (gate)
    input  q6_12        Vin,          // DC input voltage (Q6.12)
    output q6_12        v_out,
    output q6_12        i_out
);
    localparam q6_12 V_INIT_0 = '0;
    localparam q6_12 I_INIT_0 = '0;
    localparam q6_12 V_INIT_1 = '0;
    localparam q6_12 I_INIT_1 = '0;

    q6_12 v_reg, i_reg;

    logic s_k_d1;
    q6_12 v_in_s1, v_in_s2;
    assign v_in_s1 = s_k_d1 ? Vin : '0;  // pairs with B1 (= M*u_hat)
    assign v_in_s2 = s_k    ? Vin : '0;  // pairs with B2 (=   u_hat)

    logic signed [35:0] prod_v_base_a, prod_v_base_b, prod_v_base_c1, prod_v_base_c2;
    logic signed [35:0] prod_v_damp_a, prod_v_damp_b;
    logic signed [35:0] prod_i_base_a, prod_i_base_b, prod_i_base_c1, prod_i_base_c2;
    logic signed [35:0] prod_i_damp_a, prod_i_damp_b;

    q6_12 v_damp_sum, i_damp_sum;
    logic signed [35:0] prod_v_kR, prod_i_kR;

    q6_12 r1_v_state, r1_v_input, r1_v_damp;
    q6_12 r1_i_state, r1_i_input, r1_i_damp;
    q2_16 r1_kR;

    // --- STAGE 1: Mixed-Precision Multiplication ---
    always_comb begin
        prod_v_base_a  = v_reg   * C_VA;
        prod_v_base_b  = i_reg   * C_VB;
        prod_v_base_c1 = v_in_s1 * C_VC1;
        prod_v_base_c2 = v_in_s2 * C_VC2;
        prod_v_damp_a  = v_reg   * C_VD;
        prod_v_damp_b  = i_reg   * C_VE;

        prod_i_base_a  = v_reg   * C_IA;
        prod_i_base_b  = i_reg   * C_IB;
        prod_i_base_c1 = v_in_s1 * C_IC1;
        prod_i_base_c2 = v_in_s2 * C_IC2;
        prod_i_damp_a  = v_reg   * C_ID;
        prod_i_damp_b  = i_reg   * C_IE;

        v_damp_sum = q6_12'((prod_v_damp_a + prod_v_damp_b) >>> 16);
        i_damp_sum = q6_12'((prod_i_damp_a + prod_i_damp_b) >>> 16);
    end

    // --- PIPELINE LAYER 1 ---
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            r1_v_state <= V_INIT_1;
            r1_v_input <= '0;
            r1_v_damp  <= '0;
            r1_i_state <= I_INIT_1;
            r1_i_input <= '0;
            r1_i_damp  <= '0;
            r1_kR      <= '0;
            s_k_d1     <= 1'b0;
        end else begin
            r1_v_state <= q6_12'((prod_v_base_a  + prod_v_base_b ) >>> 16);
            r1_v_input <= q6_12'((prod_v_base_c1 + prod_v_base_c2) >>> 16);
            r1_v_damp  <= v_damp_sum;
            r1_i_state <= q6_12'((prod_i_base_a  + prod_i_base_b ) >>> 16);
            r1_i_input <= q6_12'((prod_i_base_c1 + prod_i_base_c2) >>> 16);
            r1_i_damp  <= i_damp_sum;
            r1_kR      <= kR;
            s_k_d1     <= s_k;
        end
    end

    // --- STAGE 2: combine pair-sums + kR multiply + final accumulation ---
    q6_12 v_next, i_next;
    always_comb begin
        prod_v_kR = r1_v_damp * r1_kR;
        prod_i_kR = r1_i_damp * r1_kR;
    end
    assign v_next = (r1_v_state + r1_v_input) + q6_12'(prod_v_kR >>> 16);
    assign i_next = (r1_i_state + r1_i_input) + q6_12'(prod_i_kR >>> 16);

    // --- PIPELINE LAYER 2 ---
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            v_reg <= V_INIT_0;
            i_reg <= I_INIT_0;
        end else begin
            v_reg <= v_next;
            i_reg <= i_next;
        end
    end

    assign v_out = v_reg;
    assign i_out = i_reg;
endmodule
