"""gen_coeffs.py - generate fixed-point coefficients for buck_lookahead.

Computes (with FIXED R, runtime Vin):
  - D       = M2 - I        (I+D form, 2x2)
  - U_HAT[s]               (single-step u_hat per switch, 2x2)
  - U2_HAT[s_now, s_next]  (look-ahead u2_hat, 4x2)
where  M       = [[1-kR-kC*hL, kC], [-hL*(2-kR-kC*hL), 1-hL*kC]]
       u_hat(s) = s * [kC*hL, hL*(2 - kC*hL)]       (= u(s)/Vin)
       M2      = M @ M
       U2_HAT[a,b] = M @ u_hat(a) + u_hat(b)

Emits buck_coeffs_pkg.sv with Q2.16 (signed 18-bit) coefficient codes and
prints float + integer for hand-verification (gate 1).
"""
from __future__ import annotations
import argparse
import numpy as np
from pathlib import Path


# ---------- plant params (compile-time constants) ----------
L_DEFAULT  = 10e-6
C_DEFAULT  = 100e-6
R_DEFAULT  = 5.0
DT_DEFAULT = 10e-9
STEPS_PER_PERIOD_DEFAULT = 100
VIN_NOM_DEFAULT = 12.0


# ---------- fixed-point format (locked by plan) ----------
COEFF_BITS = 18
COEFF_FRAC = 16
STATE_BITS = 25
STATE_FRAC = 16

COEFF_SCALE = 1 << COEFF_FRAC
COEFF_MIN   = -(1 << (COEFF_BITS - 1))
COEFF_MAX   =  (1 << (COEFF_BITS - 1)) - 1


def compute_matrices(L, C, R, dt):
    kL = dt / L
    kC = dt / C
    kR = dt / (R * C)
    hL = kL / 2.0
    M = np.array([
        [1.0 - kR - kC * hL,            kC],
        [-hL * (2.0 - kR - kC * hL),    1.0 - hL * kC]
    ])
    def u_hat(s: int) -> np.ndarray:
        return np.array([kC * hL * s, hL * (2.0 - kC * hL) * s])
    M2 = M @ M
    D  = M2 - np.eye(2)
    U_HAT  = {s: u_hat(s) for s in (0, 1)}
    U2_HAT = {(a, b): M @ u_hat(a) + u_hat(b) for a in (0, 1) for b in (0, 1)}
    return dict(kL=kL, kC=kC, kR=kR, hL=hL, M=M, M2=M2, D=D,
                U_HAT=U_HAT, U2_HAT=U2_HAT)


def q_round(x: float) -> int:
    """Round-half-up to nearest integer in Q2.16."""
    # numpy's np.round is banker's; we want round-half-up symmetric. Use floor((x*SCALE) + 0.5).
    return int(np.floor(x * COEFF_SCALE + 0.5))


def q_check(code: int, name: str) -> int:
    if not (COEFF_MIN <= code <= COEFF_MAX):
        raise ValueError(
            f"{name} code {code} outside Q{COEFF_BITS-COEFF_FRAC}.{COEFF_FRAC} "
            f"range [{COEFF_MIN},{COEFF_MAX}]"
        )
    return code


def fmt_signed_sv(code: int, width: int) -> str:
    if code >= 0:
        return f"{width}'sd{code}"
    return f"-{width}'sd{-code}"


def emit_pkg(out_path: Path, params: dict, mat: dict) -> None:
    D = mat["D"]; U_HAT = mat["U_HAT"]; U2_HAT = mat["U2_HAT"]
    D_codes  = [[q_check(q_round(float(D[r, c])), f"D[{r},{c}]") for c in (0, 1)] for r in (0, 1)]
    UH_codes = {s: [q_check(q_round(float(U_HAT[s][j])), f"U_HAT[{s}][{j}]") for j in (0, 1)] for s in (0, 1)}
    U2_codes = {k: [q_check(q_round(float(v)), f"U2_HAT{k}[{j}]") for j, v in enumerate(arr)]
                for k, arr in U2_HAT.items()}

    L  = params["L"]; C = params["C"]; R = params["R"]; dt = params["dt"]
    SPP = params["steps_per_period"]; Vin_nom = params["Vin_nom"]

    lines = []
    lines.append("// AUTO-GENERATED by gen_coeffs.py - do not edit.")
    lines.append(f"// Plant: L={L}, C={C}, R={R} ohm, dt={dt} s,")
    lines.append(f"//        steps_per_period={SPP}, Vin_nom={Vin_nom} V (R fixed).")
    lines.append(f"// Coefficients: Q{COEFF_BITS-COEFF_FRAC}.{COEFF_FRAC} signed {COEFF_BITS}-bit.")
    lines.append(f"// State:        Q{STATE_BITS-STATE_FRAC-1}.{STATE_FRAC} signed {STATE_BITS}-bit.")
    lines.append("")
    lines.append("package buck_coeffs_pkg;")
    lines.append(f"    localparam int COEFF_BITS = {COEFF_BITS};")
    lines.append(f"    localparam int COEFF_FRAC = {COEFF_FRAC};")
    lines.append(f"    localparam int STATE_BITS = {STATE_BITS};")
    lines.append(f"    localparam int STATE_FRAC = {STATE_FRAC};")
    lines.append(f"    localparam int STEPS_PER_PERIOD = {SPP};")
    lines.append("")
    lines.append("    // D = M2 - I (I+D form). One constant 2x2 matrix.")
    for r in (0, 1):
        for c in (0, 1):
            lines.append(f"    localparam logic signed [{COEFF_BITS-1}:0] D_{r}{c} = "
                         f"{fmt_signed_sv(D_codes[r][c], COEFF_BITS)};")
    lines.append("")
    lines.append("    // U_HAT[s][j]: single-step u_hat. Used during priming (cycle 1) to")
    lines.append("    // compute x[1] = U_HAT[s[0]] * Vin (because x[0] = 0).")
    for s in (0, 1):
        for j in (0, 1):
            lines.append(f"    localparam logic signed [{COEFF_BITS-1}:0] U_HAT_{s}_{j} = "
                         f"{fmt_signed_sv(UH_codes[s][j], COEFF_BITS)};")
    lines.append("")
    lines.append("    // U2_HAT[s_now][s_next][j]: 2-step input coefficient, multiplied by")
    lines.append("    // runtime Vin to form u2 = M @ u(s_now) + u(s_next).")
    for (a, b), arr in U2_codes.items():
        for j in (0, 1):
            lines.append(f"    localparam logic signed [{COEFF_BITS-1}:0] U2_HAT_{a}_{b}_{j} = "
                         f"{fmt_signed_sv(arr[j], COEFF_BITS)};")
    lines.append("")
    lines.append("endpackage")
    lines.append("")
    out_path.write_text("\n".join(lines))


def print_table(params: dict, mat: dict) -> None:
    print("Plant parameters:")
    for k in ("L", "C", "R", "dt", "steps_per_period", "Vin_nom"):
        print(f"  {k:<18} = {params[k]}")
    print()
    print("Derived (float):")
    for k in ("kL", "kC", "kR", "hL"):
        print(f"  {k:<18} = {mat[k]:.6e}")
    print(f"  M  =\n{mat['M']}")
    print(f"  M2 =\n{mat['M2']}")
    print(f"  D  = M2 - I =\n{mat['D']}")
    for s in (0, 1):
        print(f"  u_hat({s}) = {mat['U_HAT'][s]}")
    for k, v in mat["U2_HAT"].items():
        print(f"  U2_HAT{k} = {v}")
    print()
    print(f"Q{COEFF_BITS-COEFF_FRAC}.{COEFF_FRAC} integer codes  (round-half-up,  LSB = 1/{COEFF_SCALE}):")
    D = mat["D"]
    for r in (0, 1):
        for c in (0, 1):
            code = q_round(float(D[r, c]))
            print(f"  D[{r},{c}]:  float={D[r, c]:+.6e}   code={code:+d}   "
                  f"=>{code/COEFF_SCALE:+.6e}  err={code/COEFF_SCALE - D[r, c]:+.2e}")
    for s in (0, 1):
        for j in (0, 1):
            v = float(mat["U_HAT"][s][j])
            code = q_round(v)
            print(f"  U_HAT[{s}][{j}]: float={v:+.6e}   code={code:+d}   "
                  f"=>{code/COEFF_SCALE:+.6e}")
    for (a, b), arr in mat["U2_HAT"].items():
        for j in (0, 1):
            v = float(arr[j])
            code = q_round(v)
            print(f"  U2_HAT[{a},{b}][{j}]: float={v:+.6e}  code={code:+d}  "
                  f"=>{code/COEFF_SCALE:+.6e}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--L",  type=float, default=L_DEFAULT)
    ap.add_argument("--C",  type=float, default=C_DEFAULT)
    ap.add_argument("--R",  type=float, default=R_DEFAULT)
    ap.add_argument("--dt", type=float, default=DT_DEFAULT)
    ap.add_argument("--steps-per-period", type=int, default=STEPS_PER_PERIOD_DEFAULT)
    ap.add_argument("--vin-nom", type=float, default=VIN_NOM_DEFAULT)
    ap.add_argument("--out", type=Path, default=Path(__file__).resolve().parent / "buck_coeffs_pkg.sv")
    args = ap.parse_args()

    params = dict(L=args.L, C=args.C, R=args.R, dt=args.dt,
                  steps_per_period=args.steps_per_period, Vin_nom=args.vin_nom)
    mat = compute_matrices(args.L, args.C, args.R, args.dt)
    print_table(params, mat)
    emit_pkg(args.out, params, mat)
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
