"""
Generate N=3 look-ahead coefficients for the Buck (fixed R), emit SV package.
  M3 = M^3 (single constant 2x2, fixed R)
  u3[s_k,s_k1,s_k2] = M^2 u(s_k) + M u(s_k1) + u(s_k2)   (8 entries)
  Store in I+D3 form: D3 = M3 - I
  Coefficient format Q2.24 (needs cascaded DSP); state Q9.16... but for the
  multiply both operands share frac bits. We use:
     coeff: Q s_c.FRAC_C  with FRAC_C=24  (signed, ~26-bit -> 2 DSPs)
     state: Q s_s.FRAC_S  with FRAC_S=16
  product frac = FRAC_C+FRAC_S=40 -> shift right by FRAC_C=24 to land at FRAC_S=16.
  (We keep state at 16 frac bits; coeff carries the high resolution.)
"""
import numpy as np

# Fixed params
dt, L, C, R, Vin_nom = 10e-9, 10e-6, 100e-6, 5.0, 12.0
kL, kC, kR = dt/L, dt/C, dt/(R*C)
hL = kL/2

M = np.array([[1 - kR - kC*hL,        kC        ],
              [-hL*(2 - kR - kC*hL),   1 - hL*kC ]])
def u_hat(s):   # u = u_hat * Vin
    return np.array([kC*hL*s, hL*(2 - kC*hL)*s])

M2 = M @ M
M3 = M @ M2
D3 = M3 - np.eye(2)

# u3_hat (per unit Vin) for all 8 switch triples
def u3_hat(sk, sk1, sk2):
    return M2 @ u_hat(sk) + M @ u_hat(sk1) + u_hat(sk2)

FRAC_C = 24   # coefficient fractional bits
FRAC_S = 16   # state fractional bits

def code(x, frac):
    return int(round(x * (1 << frac)))

print("=== M, M2, M3 ===")
print("M =\n", M)
print("M3 =\n", M3)
print("D3 = M3 - I =\n", D3)
print()
print(f"=== Coefficient codes (Q*.{FRAC_C}) ===")
print("D3 entries:")
for r in range(2):
    for c in range(2):
        cc = code(D3[r,c], FRAC_C)
        bits = cc.bit_length()+1
        print(f"  D3[{r}][{c}] = {D3[r,c]:+.8e} -> {cc:>12d}  (~{bits} bits)")

print("\nu3_hat entries (per unit Vin), 8 switch triples:")
u3_table = {}
for sk in (0,1):
    for sk1 in (0,1):
        for sk2 in (0,1):
            val = u3_hat(sk, sk1, sk2)
            u3_table[(sk,sk1,sk2)] = val
            idx = sk*4 + sk1*2 + sk2
            print(f"  u3_hat[{sk}{sk1}{sk2}] (idx {idx}) = [{val[0]:+.8e}, {val[1]:+.8e}]")

# Emit SystemVerilog package
def fmt(cc, w=32):
    return f"{w}'sd{cc}" if cc >= 0 else f"-{w}'sd{-cc}"

lines = []
lines.append("// AUTO-GENERATED by gen_coeffs_n3.py  --  do not edit by hand")
lines.append("// Buck N=3 look-ahead coefficients (fixed R).")
lines.append(f"// Params: dt={dt}, L={L}, C={C}, R={R}, Vin_nom={Vin_nom}")
lines.append(f"// kL={kL:.6e} kC={kC:.6e} kR={kR:.6e}")
lines.append("package buck_coeffs_pkg;")
lines.append(f"  localparam int FRAC_C = {FRAC_C};  // coefficient fractional bits")
lines.append(f"  localparam int FRAC_S = {FRAC_S};  // state fractional bits")
lines.append("")
lines.append("  // D3 = M3 - I, coefficient format Q*.FRAC_C (signed)")
for r in range(2):
    for c in range(2):
        cc = code(D3[r,c], FRAC_C)
        lines.append(f"  localparam logic signed [31:0] D3_{r}{c} = {fmt(cc)};")
lines.append("")
lines.append("  // u3_hat per unit Vin, format Q*.FRAC_C (signed). Index = {s_k,s_k1,s_k2}.")
lines.append("  // Multiply by Vin (state format) at runtime.")
for (sk,sk1,sk2),val in u3_table.items():
    idx = sk*4 + sk1*2 + sk2
    cv = code(val[0], FRAC_C); ci = code(val[1], FRAC_C)
    lines.append(f"  localparam logic signed [31:0] U3V_{idx} = {fmt(cv)}; // v, s={sk}{sk1}{sk2}")
    lines.append(f"  localparam logic signed [31:0] U3I_{idx} = {fmt(ci)}; // i, s={sk}{sk1}{sk2}")
lines.append("endpackage")

with open("/home/claude/buck_coeffs_pkg.sv","w") as f:
    f.write("\n".join(lines)+"\n")
print("\nWrote buck_coeffs_pkg.sv")
