// dab3_core.sv  -  Optimized DAB look-ahead solver (module only).
//
// Identical RTL to dab3.sv, but the COEFFICIENT PACKAGE is now external and
// auto-generated by tools/twin_gen.py.  This file holds only the architecture
// (the cset_t/CIDX structural types live here, not in the package - they are
// design choices, not physics).
//
// Compile order:  gen/dab_la_pkg.sv  (generated)  THEN  dab3_core.sv
// Regenerate the package with e.g.:
//   python tools/twin_gen.py dab --L 20e-6 --Co 470e-6 --k 1.75 --dt 50e-9 \
//       --steps 200 --state-fmt Q8.24 --coef-fmt Q4.28 --out dab_LA/gen/dab_la_pkg.sv
//
// See dab3.sv for the full datapath rationale (background gamma-fold, 9-case mux).

import dab_la_pkg::*;

module dab_look_ahead_solver (
    input  logic        clk,
    input  logic        rst_n,
    input  q8_24        V1,
    input  b_pol        p1,
    input  b_pol        p2,
    input  q4_28        gamma_in,       // gamma = dt/(R*Co), runtime (slowly varying)
    output q8_24        i_L_out,
    output q8_24        V2_out
);
    localparam logic signed [63:0] HALF_LSB = 64'sh0800_0000; // +2^27 (round @ >>>28)

    // Coefficient set for one (a,b) case: M^2 matrix + gamma-folded Mb input vector.
    typedef struct packed {
        q4_28 vv, vi, iv, ii;   // M^2(a,b)   = C0 + gamma*C1
        q4_28 dv, di;           // Mb(a,b)   = D0 + gamma*D1   (V1*p1 still factored out)
    } cset_t;

    // Flat 9-entry coefficient table indices (index 9 = inert / illegal encoding).
    localparam int unsigned CIDX_PP = 0, CIDX_PN = 1, CIDX_PZ = 2, CIDX_ZP = 3,
                            CIDX_ZZ = 4, CIDX_NN = 5, CIDX_NP = 6, CIDX_NZ = 7,
                            CIDX_ZN = 8, CIDX_BAD = 9;

    function automatic q4_28 fold(input q4_28 c0, input q4_28 c1, input q4_28 g);
        logic signed [63:0] prod;
        prod = c1 * g;                                   // Q4.28 x Q4.28 = Q8.56
        fold = c0 + q4_28'((prod + HALF_LSB) >>> 28);    // + gamma-correction, back to Q4.28
    endfunction

    function automatic cset_t flip(input cset_t s);
        flip.vv =  s.vv; flip.vi = -s.vi; flip.iv = -s.iv; flip.ii = s.ii;
        flip.dv = -s.dv; flip.di =  s.di;
    endfunction

    //  BACKGROUND gamma-FOLD (off the recurrence loop; depends only on gamma) 
    cset_t fb_pp, fb_pn, fb_pz, fb_zp, fb_zz;
    always_comb begin
        fb_pp = '{ fold(C0_PP_VV,C1_PP_VV,gamma_in), fold(C0_PP_VI,C1_PP_VI,gamma_in),
                   fold(C0_PP_IV,C1_PP_IV,gamma_in), fold(C0_PP_II,C1_PP_II,gamma_in),
                   fold(D0_PP_V ,D1_PP_V ,gamma_in), fold(D0_PP_I ,D1_PP_I ,gamma_in) };
        fb_pn = '{ fold(C0_PN_VV,C1_PN_VV,gamma_in), fold(C0_PN_VI,C1_PN_VI,gamma_in),
                   fold(C0_PN_IV,C1_PN_IV,gamma_in), fold(C0_PN_II,C1_PN_II,gamma_in),
                   fold(D0_PN_V ,D1_PN_V ,gamma_in), fold(D0_PN_I ,D1_PN_I ,gamma_in) };
        fb_pz = '{ fold(C0_PZ_VV,C1_PZ_VV,gamma_in), fold(C0_PZ_VI,C1_PZ_VI,gamma_in),
                   fold(C0_PZ_IV,C1_PZ_IV,gamma_in), fold(C0_PZ_II,C1_PZ_II,gamma_in),
                   fold(D0_PZ_V ,D1_PZ_V ,gamma_in), fold(D0_PZ_I ,D1_PZ_I ,gamma_in) };
        fb_zp = '{ fold(C0_ZP_VV,C1_ZP_VV,gamma_in), fold(C0_ZP_VI,C1_ZP_VI,gamma_in),
                   fold(C0_ZP_IV,C1_ZP_IV,gamma_in), fold(C0_ZP_II,C1_ZP_II,gamma_in),
                   fold(D0_ZP_V ,D1_ZP_V ,gamma_in), fold(D0_ZP_I ,D1_ZP_I ,gamma_in) };
        fb_zz = '{ fold(C0_ZZ_VV,C1_ZZ_VV,gamma_in), fold(C0_ZZ_VI,C1_ZZ_VI,gamma_in),
                   fold(C0_ZZ_IV,C1_ZZ_IV,gamma_in), fold(C0_ZZ_II,C1_ZZ_II,gamma_in),
                   fold(D0_ZZ_V ,D1_ZZ_V ,gamma_in), fold(D0_ZZ_I ,D1_ZZ_I ,gamma_in) };
    end

    cset_t coeff_q [0:9];
    always_ff @(posedge clk) begin
        coeff_q[CIDX_PP] <= fb_pp;
        coeff_q[CIDX_PN] <= fb_pn;
        coeff_q[CIDX_PZ] <= fb_pz;
        coeff_q[CIDX_ZP] <= fb_zp;
        coeff_q[CIDX_ZZ] <= fb_zz;
        coeff_q[CIDX_NN] <= flip(fb_pp);
        coeff_q[CIDX_NP] <= flip(fb_pn);
        coeff_q[CIDX_NZ] <= flip(fb_pz);
        coeff_q[CIDX_ZN] <= flip(fb_zp);
        coeff_q[CIDX_BAD] <= '0;
    end

    //  RECURRENCE LOOP (state x[k] -> x[k+2], 2 pipeline registers) 
    q8_24 V2_reg, i_L_reg;
    b_pol p1_d1, p2_d1;

    function automatic int unsigned cidx(input b_pol a, input b_pol b);
        case ({a, b})
            {2'sb01, 2'sb01}: cidx = CIDX_PP;
            {2'sb01, 2'sb11}: cidx = CIDX_PN;
            {2'sb01, 2'sb00}: cidx = CIDX_PZ;
            {2'sb00, 2'sb01}: cidx = CIDX_ZP;
            {2'sb00, 2'sb00}: cidx = CIDX_ZZ;
            {2'sb11, 2'sb11}: cidx = CIDX_NN;
            {2'sb11, 2'sb01}: cidx = CIDX_NP;
            {2'sb11, 2'sb00}: cidx = CIDX_NZ;
            {2'sb00, 2'sb11}: cidx = CIDX_ZN;
            default:          cidx = CIDX_BAD;
        endcase
    endfunction

    cset_t cs;
    assign cs = coeff_q[cidx(p2_d1, p2)];

    q4_28 e0_v, e0_i;
    always_comb begin
        case (p2)
            2'sb01:  begin e0_v =  E0_P_V; e0_i = E0_P_I; end
            2'sb11:  begin e0_v = -E0_P_V; e0_i = E0_P_I; end
            2'sb00:  begin e0_v =  E0_Z_V; e0_i = E0_Z_I; end
            default: begin e0_v = '0;      e0_i = '0;     end
        endcase
    end

    q8_24 v1_signed_a, v1_signed_b;
    always_comb begin
        case (p1_d1)
            2'sb01:  v1_signed_a =  V1;
            2'sb11:  v1_signed_a = -V1;
            default: v1_signed_a = '0;
        endcase
        case (p1)
            2'sb01:  v1_signed_b =  V1;
            2'sb11:  v1_signed_b = -V1;
            default: v1_signed_b = '0;
        endcase
    end

    // STAGE 1: 8 Q8.24 x Q4.28 = Q12.52 multiplies
    logic signed [63:0] p_v_state_a_n, p_v_state_b_n, p_v_in_a_n, p_v_in_b_n;
    logic signed [63:0] p_i_state_a_n, p_i_state_b_n, p_i_in_a_n, p_i_in_b_n;
    always_comb begin
        p_v_state_a_n = V2_reg      * cs.vv;
        p_v_state_b_n = i_L_reg     * cs.vi;
        p_v_in_a_n    = v1_signed_a * cs.dv;
        p_v_in_b_n    = v1_signed_b * e0_v;
        p_i_state_a_n = V2_reg      * cs.iv;
        p_i_state_b_n = i_L_reg     * cs.ii;
        p_i_in_a_n    = v1_signed_a * cs.di;
        p_i_in_b_n    = v1_signed_b * e0_i;
    end

    // LAYER 1: product registers + sampled sub-step-a polarities
    logic signed [63:0] p_v_state_a, p_v_state_b, p_v_in_a, p_v_in_b;
    logic signed [63:0] p_i_state_a, p_i_state_b, p_i_in_a, p_i_in_b;
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            p_v_state_a <= '0; p_v_state_b <= '0; p_v_in_a <= '0; p_v_in_b <= '0;
            p_i_state_a <= '0; p_i_state_b <= '0; p_i_in_a <= '0; p_i_in_b <= '0;
            p1_d1 <= '0; p2_d1 <= '0;
        end else begin
            p_v_state_a <= p_v_state_a_n; p_v_state_b <= p_v_state_b_n;
            p_v_in_a    <= p_v_in_a_n;    p_v_in_b    <= p_v_in_b_n;
            p_i_state_a <= p_i_state_a_n; p_i_state_b <= p_i_state_b_n;
            p_i_in_a    <= p_i_in_a_n;    p_i_in_b    <= p_i_in_b_n;
            p1_d1 <= p1; p2_d1 <= p2;
        end
    end

    // STAGE 2: 4-term Q12.52 sum + half-LSB round (>>>28) -> Q8.24
    q8_24 V2_next, i_L_next;
    always_comb begin
        V2_next  = q8_24'((p_v_state_a + p_v_state_b + p_v_in_a + p_v_in_b + HALF_LSB) >>> 28);
        i_L_next = q8_24'((p_i_state_a + p_i_state_b + p_i_in_a + p_i_in_b + HALF_LSB) >>> 28);
    end

    // LAYER 2: core recursive state
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            V2_reg <= '0; i_L_reg <= '0;
        end else begin
            V2_reg <= V2_next; i_L_reg <= i_L_next;
        end
    end

    assign i_L_out = i_L_reg;
    assign V2_out  = V2_reg;
endmodule
