// Design: Two-Step Look-Ahead Velocity-Verlet DAB Engine - TIMING-OPTIMIZED
//         (background gamma-folding + flat 9-case coefficient mux)
//
// This is a drop-in replacement for dab2.sv (same package, module, and ports).
// It is functionally equivalent to dab2.sv but restructures the datapath to
// shorten the recurrence-loop critical path that was measured at ~23 ns.
//
// State Format:       32-bit Signed Fixed-Point (Q8.24)   range +/-128, res 6e-8
// Coefficient Format: 32-bit Signed Fixed-Point (Q4.28)   range +/-8,   res 4e-9
//
// 
// What changed vs dab2.sv (and why it is faster)
// 
// dab2's per-clock recurrence loop contained TWO serial multiplies plus a wide
// fabric adder, in only two pipeline registers:
//     base = C0*x + D0*v1a + e0*v1b           (mult + 4-add)    Stage 1
//     x'   = base + gamma*(C1*x + D1*v1a)         (2nd mult + add)  Stage 2
// The gamma-correction multiply sat *inside* the recurrence loop and ran every clock.
//
// Opt #1 - gamma is dt/(R*Co); R (the load) moves on millisecond timescales, so gamma is
//   effectively constant over thousands of clocks.  We therefore fold gamma into the
//   coefficients ONCE, in a BACKGROUND datapath that depends only on gamma (NOT on the
//   state x), and register the result:
//       C_eff = C0 + gamma*C1 ,   D_eff = D0 + gamma*D1      (computed off the hot path)
//   The recurrence then collapses to a single multiply + add:
//       x[k+2] = C_eff*x[k] + D_eff*v1a + e0*v1b
//   The gamma-multiply leaves the loop entirely; runtime-R is fully preserved.
//
// Opt #2 - dab2 stored 5 DMD-symmetry bases and recovered the 4 negated (a,b)
//   cases with a runtime `flip ? -c : c` negate sitting right in front of the
//   multipliers (a 32-bit subtract on the hot path).  Here the background folder
//   emits all 9 pre-signed coefficient sets; the hot path is a plain mux into the
//   multiplier with NO negate.  (The DMD flips are applied once, in the slow
//   folder, where their delay is irrelevant.)
//
// Net hot-path/loop: mux -> multiply -> add -> round.  One multiply per stage,
// like the original single-step engine, but still 2 algorithmic dt per loop trip
// (1 dt/clock throughput, 1-cycle output latency) - identical semantics to dab2.
//
// 
// Pipeline (II=1, 1 dt/clock, 2 recurrence-loop registers - UNCHANGED vs dab2)
// 
//   Background (off-loop, updates with gamma):
//     Fold   (comb):  C_eff/D_eff = C0/D0 + gamma*(C1/D1)  for the 5 stored bases
//     CoefReg (reg):  9 pre-signed coefficient sets (5 bases + 4 DMD-flipped)
//   Hot loop:
//     Stage 1 (comb): coeff mux (9-way) + v1 sign-mux -> 8 Q8.24xQ4.28 mults
//     Layer 1  (reg): 8 Q12.52 products + sampled (p1_d1, p2_d1)
//     Stage 2 (comb): 4-term Q12.52 add + half-LSB round (>>>28) -> x_next
//     Layer 2  (reg): V2_reg, i_L_reg
//
// Base coefficients (C0, C1, D0, D1, e0) are auto-generated by
// derive_coeffs_la2_gamma.py and are identical to dab2.sv's package.
// 

package dab_la_pkg;
    typedef logic signed [31:0] q8_24;   // state
    typedef logic signed [31:0] q4_28;   // coefficient
    typedef logic signed [1:0]  b_pol;   // bridge polarity: +1, 0, -1

    localparam q4_28 C_ONE  = 32'sh10000000; //  1.0  in Q4.28
    localparam q4_28 C_ZERO = 32'sh00000000;

    // Circuit: V1=48.0, k=1.75, L=20.0u, Co=470.0u, dt=50.0n.  R = runtime gamma.

    //  C0 - base (gamma=0) M^2(a,b), 5 unique cases [VV, VI; IV, II] 
    localparam q4_28 C0_PP_VV = 32'sh0FFFFE4B, C0_PP_VI = 32'sh0001866D,
                     C0_PP_IV = 32'shFFDC28F7, C0_PP_II = 32'sh0FFFFE4B;
    localparam q4_28 C0_PN_VV = 32'sh10000000, C0_PN_VI = 32'sh00000000,
                     C0_PN_IV = 32'sh00000000, C0_PN_II = 32'sh10000000;
    localparam q4_28 C0_PZ_VV = 32'sh0FFFFF93, C0_PZ_VI = 32'sh0000C337,
                     C0_PZ_IV = 32'shFFEE147B, C0_PZ_II = 32'sh0FFFFF93;
    localparam q4_28 C0_ZP_VV = 32'sh0FFFFF93, C0_ZP_VI = 32'sh0000C337,
                     C0_ZP_IV = 32'shFFEE147B, C0_ZP_II = 32'sh0FFFFF93;
    localparam q4_28 C0_ZZ_VV = C_ONE,         C0_ZZ_VI = C_ZERO,
                     C0_ZZ_IV = C_ZERO,        C0_ZZ_II = C_ONE;

    //  C1 - gamma-linear M^2 coefficient matrices, 5 unique cases 
    localparam q4_28 C1_PP_VV = 32'shE0000148, C1_PP_VI = 32'shFFFF3CC9,
                     C1_PP_IV = 32'sh0023D70A, C1_PP_II = 32'sh0000006D;
    localparam q4_28 C1_PN_VV = 32'shE000006D, C1_PN_VI = 32'shFFFF3CC9,
                     C1_PN_IV = 32'shFFEE147B, C1_PN_II = 32'shFFFFFF93;
    localparam q4_28 C1_PZ_VV = 32'shE000006D, C1_PZ_VI = 32'shFFFF3CC9,
                     C1_PZ_IV = 32'sh0008F5C3, C1_PZ_II = C_ZERO;
    localparam q4_28 C1_ZP_VV = 32'shE000006D, C1_ZP_VI = C_ZERO,
                     C1_ZP_IV = 32'sh001AE147, C1_ZP_II = C_ZERO;
    localparam q4_28 C1_ZZ_VV = 32'shE0000000, C1_ZZ_VI = C_ZERO,
                     C1_ZZ_IV = C_ZERO,        C1_ZZ_II = C_ZERO;

    //  D0 - base (gamma=0) Mb(a,b) input vectors [V; I], 5 unique cases 
    localparam q4_28 D0_PP_V = 32'sh000000BB, D0_PP_I = 32'sh000A3D70;
    localparam q4_28 D0_PN_V = 32'shFFFFFFC2, D0_PN_I = 32'sh000A3D71;
    localparam q4_28 D0_PZ_V = 32'sh0000003E, D0_PZ_I = 32'sh000A3D71;
    localparam q4_28 D0_ZP_V = 32'sh0000007D, D0_ZP_I = 32'sh000A3D70;
    localparam q4_28 D0_ZZ_V = C_ZERO,        D0_ZZ_I = 32'sh000A3D71;

    //  D1 - gamma-linear input vectors, 5 unique cases 
    localparam q4_28 D1_PP_V = 32'shFFFFFFC2, D1_PP_I = C_ZERO;
    localparam q4_28 D1_PN_V = 32'shFFFFFFC2, D1_PN_I = C_ZERO;
    localparam q4_28 D1_PZ_V = 32'shFFFFFFC2, D1_PZ_I = C_ZERO;
    localparam q4_28 D1_ZP_V = C_ZERO,        D1_ZP_I = C_ZERO;
    localparam q4_28 D1_ZZ_V = C_ZERO,        D1_ZZ_I = C_ZERO;

    //  e0 - second sub-step input vector b(p2_b) (gamma-independent) 
    // b(P)=[G;H], b(Z)=[0;2alpha], b(N)=[-G;H] (= V-flip of b(P), applied at source).
    localparam q4_28 E0_P_V = 32'sh0000003E, E0_P_I = 32'sh000A3D71;
    localparam q4_28 E0_Z_V = C_ZERO,        E0_Z_I = 32'sh000A3D71;

    // Coefficient set for one (a,b) case: M^2 matrix + gamma-folded Mb input vector.
    typedef struct packed {
        q4_28 vv, vi, iv, ii;   // M^2(a,b)   = C0 + gamma*C1
        q4_28 dv, di;           // Mb(a,b)*  = D0 + gamma*D1   (V1*p1 still factored out)
    } cset_t;

    // Case indices for the flat 9-entry coefficient table (index 9 = inert).
    localparam int unsigned CIDX_PP = 0, CIDX_PN = 1, CIDX_PZ = 2, CIDX_ZP = 3,
                            CIDX_ZZ = 4, CIDX_NN = 5, CIDX_NP = 6, CIDX_NZ = 7,
                            CIDX_ZN = 8, CIDX_BAD = 9;
endpackage

import dab_la_pkg::*;

module dab_look_ahead_solver (
    input  logic        clk,
    input  logic        rst_n,

    // Plant inputs (Q8.24)
    input  q8_24        V1,             // Primary DC link voltage
    input  b_pol        p1,             // Primary bridge polarity (sub-step b)
    input  b_pol        p2,             // Secondary bridge polarity (sub-step b)
    input  q4_28        gamma_in,       // gamma = dt/(R*Co), runtime (slowly varying)

    // Outputs (Q8.24)
    output q8_24        i_L_out,
    output q8_24        V2_out
);
    localparam logic signed [63:0] HALF_LSB = 64'sh0800_0000; // +2^27 (round @ >>>28)

    // Round-to-nearest convert of a Q*.56 (or Q12.52) 64-bit product/sum down by 28.
    function automatic q4_28 fold(input q4_28 c0, input q4_28 c1, input q4_28 g);
        logic signed [63:0] prod;
        prod = c1 * g;                                   // Q4.28 x Q4.28 = Q8.56
        fold = c0 + q4_28'((prod + HALF_LSB) >>> 28);    // + gamma-correction, back to Q4.28
    endfunction

    // DMD off-diagonal / V-entry sign flip:  D*X*D negates VI,IV;  E*v negates V.
    function automatic cset_t flip(input cset_t s);
        flip.vv =  s.vv; flip.vi = -s.vi; flip.iv = -s.iv; flip.ii = s.ii;
        flip.dv = -s.dv; flip.di =  s.di;
    endfunction

    // 
    // BACKGROUND gamma-FOLD (off the recurrence loop - depends only on gamma, not on x)
    // 
    // These multiplies update only when the controller changes gamma (i.e. when the
    // load R changes, on a ~ms cadence).  They can be heavily time-multiplexed or
    // multicycle-constrained in synthesis; nothing here feeds back through state.
    cset_t fb_pp, fb_pn, fb_pz, fb_zp, fb_zz;   // folded 5 stored bases (comb)
    always_comb begin
        fb_pp = '{ fold(C0_PP_VV,C1_PP_VV,gamma_in), fold(C0_PP_VI,C1_PP_VI,gamma_in),
                   fold(C0_PP_IV,C1_PP_IV,gamma_in), fold(C0_PP_II,C1_PP_II,gamma_in),
                   fold(D0_PP_V ,D1_PP_V ,gamma_in), fold(D0_PP_I ,D1_PP_I ,gamma_in) };
        fb_pn = '{ fold(C0_PN_VV,C1_PN_VV,gamma_in), fold(C0_PN_VI,C1_PN_VI,gamma_in),
                   fold(C0_PN_IV,C1_PN_IV,gamma_in), fold(C0_PN_II,C1_PN_II,gamma_in),
                   fold(D0_PN_V ,D1_PN_V ,gamma_in), fold(D0_PN_I ,D1_PN_I ,gamma_in) };
        fb_pz = '{ fold(C0_PZ_VV,C1_PZ_VV,gamma_in), fold(C0_PZ_VI,C1_PZ_VI,gamma_in),
                   fold(C0_PZ_IV,C1_PZ_IV,gamma_in), fold(C0_PZ_II,C1_PZ_II,gamma_in),
                   fold(D0_PZ_V ,D1_PZ_V ,gamma_in), fold(D0_PZ_I ,D1_PZ_I ,gamma_in) };
        fb_zp = '{ fold(C0_ZP_VV,C1_ZP_VV,gamma_in), fold(C0_ZP_VI,C1_ZP_VI,gamma_in),
                   fold(C0_ZP_IV,C1_ZP_IV,gamma_in), fold(C0_ZP_II,C1_ZP_II,gamma_in),
                   fold(D0_ZP_V ,D1_ZP_V ,gamma_in), fold(D0_ZP_I ,D1_ZP_I ,gamma_in) };
        fb_zz = '{ fold(C0_ZZ_VV,C1_ZZ_VV,gamma_in), fold(C0_ZZ_VI,C1_ZZ_VI,gamma_in),
                   fold(C0_ZZ_IV,C1_ZZ_IV,gamma_in), fold(C0_ZZ_II,C1_ZZ_II,gamma_in),
                   fold(D0_ZZ_V ,D1_ZZ_V ,gamma_in), fold(D0_ZZ_I ,D1_ZZ_I ,gamma_in) };
    end

    // Registered flat 9-case table (5 bases + 4 DMD-flipped), pre-signed.
    // Index 9 is held at zero so an illegal {a,b} encoding produces an inert step.
    cset_t coeff_q [0:9];
    always_ff @(posedge clk) begin
        coeff_q[CIDX_PP] <= fb_pp;
        coeff_q[CIDX_PN] <= fb_pn;
        coeff_q[CIDX_PZ] <= fb_pz;
        coeff_q[CIDX_ZP] <= fb_zp;
        coeff_q[CIDX_ZZ] <= fb_zz;
        coeff_q[CIDX_NN] <= flip(fb_pp);   // NN <-> PP
        coeff_q[CIDX_NP] <= flip(fb_pn);   // NP <-> PN
        coeff_q[CIDX_NZ] <= flip(fb_pz);   // NZ <-> PZ
        coeff_q[CIDX_ZN] <= flip(fb_zp);   // ZN <-> ZP
        coeff_q[CIDX_BAD] <= '0;
    end

    // 
    // RECURRENCE LOOP  (state x[k] -> x[k+2], 2 pipeline registers, 1 dt/clock)
    // 
    q8_24 V2_reg, i_L_reg;    // Layer-2 state
    b_pol p1_d1, p2_d1;       // sub-step-a (previous-clock) polarities

    //  Map {p2_d1, p2} -> flat case index (no negate; selection only) 
    function automatic int unsigned cidx(input b_pol a, input b_pol b);
        case ({a, b})
            {2'sb01, 2'sb01}: cidx = CIDX_PP;
            {2'sb01, 2'sb11}: cidx = CIDX_PN;
            {2'sb01, 2'sb00}: cidx = CIDX_PZ;
            {2'sb00, 2'sb01}: cidx = CIDX_ZP;
            {2'sb00, 2'sb00}: cidx = CIDX_ZZ;
            {2'sb11, 2'sb11}: cidx = CIDX_NN;
            {2'sb11, 2'sb01}: cidx = CIDX_NP;
            {2'sb11, 2'sb00}: cidx = CIDX_NZ;
            {2'sb00, 2'sb11}: cidx = CIDX_ZN;
            default:          cidx = CIDX_BAD;
        endcase
    endfunction

    cset_t cs;                       // selected coefficient set (registered table)
    assign cs = coeff_q[cidx(p2_d1, p2)];

    //  e0 (second sub-step input vector b(p2_b)); gamma-independent, p2-only 
    q4_28 e0_v, e0_i;
    always_comb begin
        case (p2)
            2'sb01:  begin e0_v =  E0_P_V; e0_i = E0_P_I; end   // b(P)
            2'sb11:  begin e0_v = -E0_P_V; e0_i = E0_P_I; end   // b(N) = V-flip of b(P)
            2'sb00:  begin e0_v =  E0_Z_V; e0_i = E0_Z_I; end   // b(Z)
            default: begin e0_v = '0;      e0_i = '0;     end
        endcase
    end

    //  Signed V1 for each sub-step (p1 sign-mux) 
    q8_24 v1_signed_a, v1_signed_b;
    always_comb begin
        case (p1_d1)
            2'sb01:  v1_signed_a =  V1;
            2'sb11:  v1_signed_a = -V1;
            default: v1_signed_a = '0;
        endcase
        case (p1)
            2'sb01:  v1_signed_b =  V1;
            2'sb11:  v1_signed_b = -V1;
            default: v1_signed_b = '0;
        endcase
    end

    //  STAGE 1 (comb): 8 parallel Q8.24 x Q4.28 = Q12.52 multiplies 
    logic signed [63:0] p_v_state_a_n, p_v_state_b_n, p_v_in_a_n, p_v_in_b_n;
    logic signed [63:0] p_i_state_a_n, p_i_state_b_n, p_i_in_a_n, p_i_in_b_n;

    always_comb begin
        // V2 row:  C_eff_vv*V2 + C_eff_vi*iL + D_eff_v*v1a + e0_v*v1b
        p_v_state_a_n = V2_reg      * cs.vv;
        p_v_state_b_n = i_L_reg     * cs.vi;
        p_v_in_a_n    = v1_signed_a * cs.dv;
        p_v_in_b_n    = v1_signed_b * e0_v;
        // i_L row:  C_eff_iv*V2 + C_eff_ii*iL + D_eff_i*v1a + e0_i*v1b
        p_i_state_a_n = V2_reg      * cs.iv;
        p_i_state_b_n = i_L_reg     * cs.ii;
        p_i_in_a_n    = v1_signed_a * cs.di;
        p_i_in_b_n    = v1_signed_b * e0_i;
    end

    //  LAYER 1 (reg): product registers + sampled sub-step-a polarities 
    logic signed [63:0] p_v_state_a, p_v_state_b, p_v_in_a, p_v_in_b;
    logic signed [63:0] p_i_state_a, p_i_state_b, p_i_in_a, p_i_in_b;

    always_ff @(posedge clk) begin
        if (!rst_n) begin
            p_v_state_a <= '0; p_v_state_b <= '0; p_v_in_a <= '0; p_v_in_b <= '0;
            p_i_state_a <= '0; p_i_state_b <= '0; p_i_in_a <= '0; p_i_in_b <= '0;
            p1_d1 <= '0; p2_d1 <= '0;
        end else begin
            p_v_state_a <= p_v_state_a_n; p_v_state_b <= p_v_state_b_n;
            p_v_in_a    <= p_v_in_a_n;    p_v_in_b    <= p_v_in_b_n;
            p_i_state_a <= p_i_state_a_n; p_i_state_b <= p_i_state_b_n;
            p_i_in_a    <= p_i_in_a_n;    p_i_in_b    <= p_i_in_b_n;
            p1_d1 <= p1; p2_d1 <= p2;     // become sub-step-a polarities next clock
        end
    end

    //  STAGE 2 (comb): 4-term Q12.52 sum + half-LSB round (>>>28) -> Q8.24 
    q8_24 V2_next, i_L_next;
    always_comb begin
        V2_next  = q8_24'((p_v_state_a + p_v_state_b + p_v_in_a + p_v_in_b + HALF_LSB) >>> 28);
        i_L_next = q8_24'((p_i_state_a + p_i_state_b + p_i_in_a + p_i_in_b + HALF_LSB) >>> 28);
    end

    //  LAYER 2 (reg): core recursive state 
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            V2_reg <= '0; i_L_reg <= '0;
        end else begin
            V2_reg <= V2_next; i_L_reg <= i_L_next;
        end
    end

    assign i_L_out = i_L_reg;
    assign V2_out  = V2_reg;

endmodule
