#!/usr/bin/env python3
"""
Derive γ-decomposed 2-step look-ahead coefficients for the DAB Verlet engine
used by dab2.sv (dab_la_pkg).

Recurrence (per algorithmic dt):
    i_half  = i + α·(p1·V1 − k·p2·V2)
    V2_next = V2·(1 − γ) + β·k·p2·i_half
    i_next  = i_half + α·(p1·V1 − k·p2·V2_next)

In matrix form: x[n+1] = M(p2)·x[n] + b(p2)·p1·V1,  x = [V2; i].

γ-decomposition (R-dependence factored out, γ = Δt/(R·Co)):
    M(p2)   = M0(p2) + γ·M1(p2)
    M²(a,b) = M(b)·M(a)
            = M0(b)·M0(a) + γ·(M0(b)·M1(a) + M1(b)·M0(a)) + γ²·M1(b)·M1(a)
            ≈ C0(a,b) + γ·C1(a,b)            (γ² ~10⁻¹⁰, below LSB)
    Mb(a,b) = M(b)·b(a)
            = M0(b)·b(a) + γ·M1(b)·b(a)
            =  D0(a,b)   + γ·D1(a,b)
    b(b)    = e0(b)                          (γ-independent)

DMD symmetry — M(−p2) = D·M(p2)·D with D = diag(1, −1).
That collapses 9 (a,b) pairs to 5 stored bases: PP, PN, PZ, ZP, ZZ.
The negated cases NN, NP, NZ, ZN reuse those bases with off-diagonal /
V-entry sign-flips applied at the source in the SV mux.

Outputs Q4.28 (32-bit signed) hex constants in the format expected by
the dab_la_pkg block of dab2.sv.
"""
import numpy as np

# ── Circuit parameters (match dab_ref.py) ─────────────────────────────────
V1 = 48.0
k  = 1.75
L  = 20e-6
Co = 470e-6
dt = 20e-9

# Used only for the sanity check below; γ is a runtime input in the engine.
Rload_check = 10.0

alpha = dt / (2.0 * L)
beta  = dt / Co
gamma_check = dt / (Rload_check * Co)


def M0(p2):
    """γ-independent piece of the single-step transition matrix."""
    p2sq = p2 * p2
    return np.array([
        [1.0 - alpha*beta*k*k*p2sq,         beta*k*p2                ],
        [-alpha*k*p2*(2.0 - alpha*beta*k*k*p2sq),  1.0 - alpha*beta*k*k*p2sq],
    ])


def M1(p2):
    """Coefficient of γ in M(p2).  M1 has rank 1: right column is zero."""
    return np.array([
        [-1.0,        0.0],
        [alpha*k*p2,  0.0],
    ])


def M(p2, g):
    return M0(p2) + g * M1(p2)


def bvec(p2):
    """Input-coupling vector (γ-independent).  V1 and p1 factored out."""
    p2sq = p2 * p2
    return np.array([
        alpha * beta * k * p2,
        2.0 * alpha - alpha*alpha*beta*k*k*p2sq,
    ])


# ── Q4.28 helpers ─────────────────────────────────────────────────────────
Q428_SCALE = 1 << 28


def to_q428(x):
    q = int(round(x * Q428_SCALE))
    if q < 0:
        q += 1 << 32
    if q < 0 or q > 0xFFFFFFFF:
        raise ValueError(f"Q4.28 overflow: x={x}, q={q:#x}")
    return q


def hx(x):
    return f"32'sh{to_q428(x):08X}"


# ── Generate the 5 stored bases ───────────────────────────────────────────
# Stored (a, b) pairs:
BASES = [
    ('PP', +1, +1),
    ('PN', +1, -1),
    ('PZ', +1,  0),
    ('ZP',  0, +1),
    ('ZZ',  0,  0),
]


def fmt_const(name, val, comment_val=None):
    return f"    localparam q4_28 {name:<10s} = {hx(val)}; // {(comment_val if comment_val is not None else val):+.6e}"


print("// ── Auto-generated by derive_coeffs_la2_gamma.py — do not hand-edit ──")
print(f"// Circuit: V1={V1}, k={k}, L={L*1e6}u, Co={Co*1e6}u, dt={dt*1e9}n")
print(f"// alpha={alpha:.6e}  beta={beta:.6e}  (γ is a runtime input)")
print()

print("// ═══ C0 — base (γ=0) M²(a,b) values, 5 unique cases ═════════════════════")
for tag, a, b in BASES:
    C0 = M0(b) @ M0(a)
    print(f"    // C0({tag}) = M0({a:+d}) @ M0({a:+d})  → [VV, VI; IV, II]")
    print(fmt_const(f"C0_{tag}_VV", C0[0,0]))
    print(fmt_const(f"C0_{tag}_VI", C0[0,1]))
    print(fmt_const(f"C0_{tag}_IV", C0[1,0]))
    print(fmt_const(f"C0_{tag}_II", C0[1,1]))
    print()

print("// ═══ C1 — γ-linear M² coefficient matrices, 5 unique cases ══════════════")
for tag, a, b in BASES:
    C1 = M0(b) @ M1(a) + M1(b) @ M0(a)
    print(f"    // C1({tag}) = M0({b:+d})·M1({a:+d}) + M1({b:+d})·M0({a:+d})")
    print(fmt_const(f"C1_{tag}_VV", C1[0,0]))
    print(fmt_const(f"C1_{tag}_VI", C1[0,1]))
    print(fmt_const(f"C1_{tag}_IV", C1[1,0]))
    print(fmt_const(f"C1_{tag}_II", C1[1,1]))
    print()

print("// ═══ D0 — base (γ=0) Mb(a,b) input vectors, 5 unique cases ══════════════")
for tag, a, b in BASES:
    D0 = M0(b) @ bvec(a)
    print(f"    // D0({tag}) = M0({b:+d}) · b({a:+d})")
    print(fmt_const(f"D0_{tag}_V", D0[0]))
    print(fmt_const(f"D0_{tag}_I", D0[1]))
    print()

print("// ═══ D1 — γ-linear input vectors, 5 unique cases ════════════════════════")
for tag, a, b in BASES:
    D1 = M1(b) @ bvec(a)
    print(f"    // D1({tag}) = M1({b:+d}) · b({a:+d})")
    print(fmt_const(f"D1_{tag}_V", D1[0]))
    print(fmt_const(f"D1_{tag}_I", D1[1]))
    print()

print("// ═══ e0 — second sub-step input vector b(p2_b), positive case + zero ════")
# Only the P and Z bases are stored; b(N) = E·b(P) with E = diag(-1, 1).
bP = bvec(+1)
bZ = bvec(0)
print(f"    // e0(P) = b(+1)")
print(fmt_const("E0_P_V", bP[0]))
print(fmt_const("E0_P_I", bP[1]))
print(f"    // e0(Z) = b(0)")
print(fmt_const("E0_Z_V", bZ[0]))
print(fmt_const("E0_Z_I", bZ[1]))

# ── DMD symmetry verification ─────────────────────────────────────────────
print()
print("// ── DMD symmetry checks ─────────────────────────────────────────────")
D = np.diag([1.0, -1.0])
E = np.diag([-1.0, 1.0])
P2 = [+1, 0, -1]
worst_M = worst_M2 = worst_b = 0.0
for p in P2:
    err = np.max(np.abs(M0(-p) - D @ M0(p) @ D))
    worst_M = max(worst_M, err)
for a in P2:
    for b in P2:
        lhs = M0(b) @ M0(a)
        rhs = D @ (M0(-b) @ M0(-a)) @ D
        worst_M2 = max(worst_M2, np.max(np.abs(lhs - rhs)))
for p in P2:
    worst_b = max(worst_b, np.max(np.abs(bvec(-p) - E @ bvec(p))))
print(f"//   |M0(−p2) − D·M0(p2)·D|_∞     = {worst_M:.3e}")
print(f"//   |M0(b)M0(a) − D·M0(−b)M0(−a)·D|_∞ = {worst_M2:.3e}")
print(f"//   |b(−p2) − E·b(p2)|_∞         = {worst_b:.3e}")

# ── Sanity: γ-decomposition vs direct M² for each (a,b) at R=10 ───────────
print(f"// ── Decomposition error @ R={Rload_check} (γ={gamma_check:.3e}) ─────────")
x0 = np.array([5.0, 1.0])
v1a, v1b = +V1, +V1
worst_C = worst_D = 0.0
for a in P2:
    for b in P2:
        # γ truth (single-step recursion applied twice with γ in M):
        x_int    = M(a, gamma_check) @ x0 + bvec(a) * v1a
        x_truth  = M(b, gamma_check) @ x_int + bvec(b) * v1b
        # γ-decomposition (what dab2.sv computes):
        C0 = M0(b) @ M0(a)
        C1 = M0(b) @ M1(a) + M1(b) @ M0(a)
        D0 = M0(b) @ bvec(a)
        D1 = M1(b) @ bvec(a)
        e0 = bvec(b)
        x_dec = (C0 + gamma_check * C1) @ x0 \
              + (D0 + gamma_check * D1) * v1a \
              + e0 * v1b
        err = np.abs(x_truth - x_dec)
        worst_C = max(worst_C, err[0])
        worst_D = max(worst_D, err[1])
print(f"//   max |V2_truth − V2_decomp| = {worst_C:.3e}  (γ² omitted)")
print(f"//   max |i_truth  − i_decomp|  = {worst_D:.3e}")
print(f"//   Q4.28 LSB ≈ {1.0/Q428_SCALE:.3e}, Q8.24 LSB ≈ {1.0/(1<<24):.3e}")
