#!/usr/bin/env python3
"""
Derive 2-step look-ahead coefficients for the DAB Verlet engine.

Recurrence (DAB.py):
    i_half  = i + alpha*(p1*V1 - k*p2*V2)
    V2_next = V2 + beta*k*p2*i_half - gamma*V2
    i_next  = i_half + alpha*(p1*V1 - k*p2*V2_next)

State x = [V2, i].  In closed matrix form for one dt step:
    x[n+1] = M(p2[n]) * x[n] + b(p2[n]) * p1[n] * V1

2-step look-ahead (sub-step 'a' = n, sub-step 'b' = n+1):
    x[n+2] = M(p2_b) * M(p2_a) * x[n]
           + M(p2_b) * b(p2_a) * p1_a * V1     (sub-step a input)
           +              b(p2_b) * p1_b * V1  (sub-step b input)

So each cycle of the pipelined engine advances 2 algorithmic dt.

This script emits Q4.28 hex constants for the SV package (dab_la_pkg):
  - M_combined[p2_a, p2_b] (2x2)              : 9 sets x 4 entries = 36 constants
  - Mb_combined[p2_a, p2_b] (2-vec, p1=+1)    : 9 sets x 2 entries = 18 constants
  - b[p2_b] (2-vec, p1=+1)                    : 3 sets x 2 entries =  6 constants
"""
import numpy as np

# ── Circuit parameters (match DAB.py / dab_ref.py) ────────────────────────
V1     = 48.0
k      = 1.75
L      = 20e-6
Co     = 470e-6
Rload  = 10.0
dt     = 50e-9       # algorithmic dt (per sub-step, per single-step Verlet)

alpha = dt / (2.0 * L)
beta  = dt / Co
gamma = dt / (Rload * Co)


def M(p2):
    """Single-step state-transition matrix M(p2).  x_next = M*x + b*p1*V1."""
    p2sq = p2 * p2  # 0 for p2=0, 1 for |p2|=1
    return np.array([
        [1.0 - gamma - alpha*beta*k*k*p2sq,  beta*k*p2                              ],
        [-alpha*k*p2*(2.0 - gamma - alpha*beta*k*k*p2sq),  1.0 - alpha*beta*k*k*p2sq],
    ])


def b(p2):
    """Input-coupling vector with p1 *and* V1 factored out.
    SV multiplies the resulting coefficient by v1_signed = p1 * V1 (Q8.24 input)."""
    p2sq = p2 * p2
    return np.array([
        alpha * beta * k * p2,
        2.0 * alpha - alpha*alpha*beta*k*k*p2sq,
    ])


# ── Q4.28 conversion helpers ──────────────────────────────────────────────
Q428_SCALE = 1 << 28


def to_q428(x):
    """Round-to-nearest, two's complement 32-bit."""
    q = int(round(x * Q428_SCALE))
    if q < 0:
        q += 1 << 32
    if q < 0 or q > 0xFFFFFFFF:
        raise ValueError(f"Q4.28 overflow: x={x}, q={q:#x}")
    return q


def fmt(q, hint=""):
    return f"32'sh{q:08X}" + (f"  // {hint}" if hint else "")


# ── Generate constants ────────────────────────────────────────────────────
P2_VALS = [+1, 0, -1]

# Mapping convention used in the SV case statement:
#   key {p2_a, p2_b}  with  p2 ∈ {2'sb01 (=+1), 2'sb00 (=0), 2'sb11 (=-1)}.
def p2_tag(p2):
    return {+1: 'P', 0: 'Z', -1: 'N'}[p2]


lines = []
lines.append("// === Auto-generated by derive_coeffs.py — do not hand-edit ===")
lines.append(f"// Circuit: V1={V1}, k={k}, L={L*1e6}u, Co={Co*1e6}u, R={Rload}, dt={dt*1e9}n")
lines.append(f"// alpha={alpha:.6e}  beta={beta:.6e}  gamma={gamma:.6e}")
lines.append("")

# --- M² entries: 4 entries per (p2_a, p2_b) ---
lines.append("// === M_combined[p2_a, p2_b] = M(p2_b) @ M(p2_a) ===")
for p2a in P2_VALS:
    for p2b in P2_VALS:
        Mc = M(p2b) @ M(p2a)
        tag = f"M2_{p2_tag(p2a)}{p2_tag(p2b)}"  # sub-step a then b
        for ri, row in enumerate(['V', 'I']):
            for ci, col in enumerate(['V', 'I']):
                name = f"C_{tag}_{row}{col}"
                lines.append(f"localparam q4_28 {name:14s} = {fmt(to_q428(Mc[ri,ci]), f'{Mc[ri,ci]:+.6e}')};")
        lines.append("")

# --- Mb entries: 2 entries per (p2_a, p2_b)  (SV multiplies by v1_signed_a = p1_a*V1) ---
lines.append("// === Mb_combined[p2_a, p2_b] = M(p2_b) @ b(p2_a)  (V1 *and* p1_a factored out) ===")
for p2a in P2_VALS:
    for p2b in P2_VALS:
        Mb = M(p2b) @ b(p2a)
        tag = f"MB_{p2_tag(p2a)}{p2_tag(p2b)}"
        for ri, row in enumerate(['V', 'I']):
            name = f"C_{tag}_{row}"
            lines.append(f"localparam q4_28 {name:14s} = {fmt(to_q428(Mb[ri]), f'{Mb[ri]:+.6e}')};")
        lines.append("")

# --- b entries: 2 entries per p2_b ---
lines.append("// === b[p2_b]  (V1 *and* p1_b factored out; SV multiplies by v1_signed_b = p1_b*V1) ===")
for p2b in P2_VALS:
    bv = b(p2b)
    tag = f"B_{p2_tag(p2b)}"
    for ri, row in enumerate(['V', 'I']):
        name = f"C_{tag}_{row}"
        lines.append(f"localparam q4_28 {name:14s} = {fmt(to_q428(bv[ri]), f'{bv[ri]:+.6e}')};")
    lines.append("")


print('\n'.join(lines))


# ── Sanity check: verify M² * x + Mb*v1_a + b*v1_b matches running M twice ──
print("// ──────────────────────────────────────────────")
print("// Sanity (Python float, p1_a=p1_b=+1, p2_a=+1, p2_b=+1, V1=48):")
x0 = np.array([5.0, 1.0])
p1a, p1b = +1, +1
p2a, p2b = +1, +1
v1a, v1b = p1a * V1, p1b * V1
# 2-step direct (single-step recursion applied twice):
x_int      = M(p2a) @ x0  + b(p2a) * v1a
x2_direct  = M(p2b) @ x_int + b(p2b) * v1b
# 2-step via combined coefficients:
x2_combined = (M(p2b) @ M(p2a)) @ x0 + (M(p2b) @ b(p2a)) * v1a + b(p2b) * v1b
print(f"// direct:   V2={x2_direct[0]:+.10f}  i={x2_direct[1]:+.10f}")
print(f"// combined: V2={x2_combined[0]:+.10f}  i={x2_combined[1]:+.10f}")
print(f"// |diff|:   {np.max(np.abs(x2_direct - x2_combined)):.3e}  (should be ~0)")
